create windows-xp
set windows-xp personality "Windows XP Professional SP1"
set windows-xp default tcp action reset
add windows-xp tcp port 80 open
add windows-xp tcp port 135 open
add windows-xp tcp port 445 open
bind 192.168.0.125 windows-xp
