# Scenario 1 - Windows Host
create windows
set windows personality "Microsoft Windows XP Professional"
set windows default tcp action reset
add windows tcp port 80 open
add windows tcp port 135 open
add windows tcp port 445 open

# Scenario 2 - Linux Host
create linux
set linux personality "Linux 2.4.20"
set linux default tcp action reset
add linux tcp port 22 open
add linux tcp port 80 open

# Bind each to an IP
bind 192.168.0.10 windows
bind 192.168.0.20 linux
