# Scenario 1 - Windows Host
create windows
set windows personality "Microsoft Windows XP Professional"
set windows default tcp action reset
set windows default udp action reset
add windows tcp port 80 open
add windows tcp port 135 open
add windows tcp port 445 open

# Scenario 2 - Linux Host
create linux
set linux personality "Linux 2.4.20"
set linux default tcp action reset
set linux default udp action reset
add linux tcp port 22 proxy 127.0.0.1:2222
add linux tcp port 80 open

# Scenario 3 - Vulnerable Web Server
create websrv
set websrv personality "Linux 2.6.18"
set websrv default tcp action reset
set websrv default udp action reset
add websrv tcp port 80 proxy 127.0.0.1:8080
add websrv tcp port 443 open

# Bind each to an IP
bind 192.168.0.10 windows
bind 192.168.0.20 linux
bind 192.168.0.30 websrv